# The following variables contains the files used by the different stages of the build process.
set(TP5_IpGeN_config_1_config_1_toolchain_FILE_TYPE_assemble)
set_source_files_properties(${TP5_IpGeN_config_1_config_1_toolchain_FILE_TYPE_assemble} PROPERTIES LANGUAGE ASM)
set(TP5_IpGeN_config_1_config_1_toolchain_FILE_TYPE_assembleWithPreprocess "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/tcpip_helper_c32.S")
set_source_files_properties(${TP5_IpGeN_config_1_config_1_toolchain_FILE_TYPE_assembleWithPreprocess} PROPERTIES LANGUAGE ASM)
set(TP5_IpGeN_config_1_config_1_toolchain_FILE_TYPE_compile
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../bsp/pic32mx_skes/Mc32CoreTimer.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../bsp/pic32mx_skes/Mc32Delays.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../bsp/pic32mx_skes/Mc32DriverAdc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../bsp/pic32mx_skes/Mc32DriverAdcAlt.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../bsp/pic32mx_skes/Mc32DriverLcd.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../bsp/pic32mx_skes/bsp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/aes.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/arc4.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/asm.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/asn.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/coding.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/compress.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/crypto.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/des3.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/ecc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/error.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/hash.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/hmac.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/integer.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/logging.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/md5.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/memory.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/misc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/pwdbased.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/random.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/rsa.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/sha.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/sha256.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/sha512.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/tfm.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/wc_port.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/wolfmath.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/adler32.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/compress.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/crc32.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/deflate.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/infback.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/inffast.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/inflate.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/inftrees.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/trees.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/uncompr.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/crypto/src/zlib-1.2.7/zutil.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/driver/ethmac/src/dynamic/drv_ethmac.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/driver/ethmac/src/dynamic/drv_ethmac_lib.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/driver/ethphy/src/dynamic/drv_ethphy.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/driver/ethphy/src/dynamic/drv_extphy_dp83848.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/driver/miim/src/dynamic/drv_miim.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/driver/tmr/src/dynamic/drv_tmr.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/driver/usb/usbfs/src/dynamic/drv_usbfs.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/driver/usb/usbfs/src/dynamic/drv_usbfs_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/driver/usb/usbhs/src/dynamic/drv_usbhs.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/driver/usb/usbhs/src/dynamic/drv_usbhs_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/system/command/src/sys_command.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/system/console/src/sys_console.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/system/console/src/sys_console_usb_cdc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/system/debug/src/sys_debug.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/system/int/src/sys_int_pic32.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/system/random/src/sys_random.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/system/tmr/src/sys_tmr.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/arp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/common/helpers.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/dhcp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/dns.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/hash_fnv.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/icmp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/ipv4.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/nbns.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/oahash.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/tcp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/tcpip_announce.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/tcpip_commands.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/tcpip_heap_alloc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/tcpip_heap_internal.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/tcpip_helpers.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/tcpip_manager.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/tcpip_notify.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/tcpip_packet.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/udp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/zero_conf_helper.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/tcpip/src/zero_conf_link_local.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/usb/src/dynamic/usb_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/usb/src/dynamic/usb_device_cdc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../framework/usb/src/dynamic/usb_device_cdc_acm.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/Generateur.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/GesPec12.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/Mc32Debounce.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/Mc32NVMUtil.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/Mc32SpiUtil.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/Mc32gestSPiDac.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/MenuGen.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/app.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/appgen.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/main.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/system_config/pic32mx_eth_sk2/framework/driver/tmr/src/drv_tmr_static.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/system_config/pic32mx_eth_sk2/framework/system/clk/src/sys_clk_pic32mx.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/system_config/pic32mx_eth_sk2/framework/system/devcon/src/sys_devcon.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/system_config/pic32mx_eth_sk2/framework/system/devcon/src/sys_devcon_pic32mx.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/system_config/pic32mx_eth_sk2/framework/system/ports/src/sys_ports_static.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/system_config/pic32mx_eth_sk2/framework/system/reset/src/sys_reset.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/system_config/pic32mx_eth_sk2/system_exceptions.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/system_config/pic32mx_eth_sk2/system_init.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/system_config/pic32mx_eth_sk2/system_interrupt.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../firmware/src/system_config/pic32mx_eth_sk2/system_tasks.c")
set_source_files_properties(${TP5_IpGeN_config_1_config_1_toolchain_FILE_TYPE_compile} PROPERTIES LANGUAGE C)
set(TP5_IpGeN_config_1_config_1_toolchain_FILE_TYPE_compile_cpp)
set_source_files_properties(${TP5_IpGeN_config_1_config_1_toolchain_FILE_TYPE_compile_cpp} PROPERTIES LANGUAGE CXX)
set(TP5_IpGeN_config_1_config_1_toolchain_FILE_TYPE_link "${CMAKE_CURRENT_SOURCE_DIR}/../../../../../../bin/framework/peripheral/PIC32MX795F512L_peripherals.a")

# The (internal) path to the resulting build image.
set(TP5_IpGeN_config_1_internal_image_name "${CMAKE_CURRENT_SOURCE_DIR}/../../../_build/TP5_IpGeN/config_1/config_1.elf")

# The name of the resulting image, including namespace for configuration.
set(TP5_IpGeN_config_1_image_name "TP5_IpGeN_config_1_config_1.elf")

# The name of the image, excluding the namespace for configuration.
set(TP5_IpGeN_config_1_original_image_name "config_1.elf")

# The output directory of the final image.
set(TP5_IpGeN_config_1_output_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../../out/TP5_IpGeN")
